// Types et constantes pour le système de personnages WoW
// Classes disponibles
export const CLASSES = {
    warrior: {
        id: "warrior",
        name: "Guerrier",
        description: "Maître du combat au corps à corps, utilise la rage pour déchaîner des attaques dévastatrices.",
        primaryStat: "strength",
        icon: "⚔️",
        color: "#C79C6E",
        baseHP: 120,
        baseMP: 0,
        availableFor: {
            alliance: ["human", "dwarf", "night-elf", "gnome", "draenei", "worgen"],
            horde: ["orc", "undead", "tauren", "troll", "blood-elf", "goblin"],
        },
        energyName: "🔥 Rage",
        armorType: "plate",
        weaponType: ["sword", "axe", "mace"],
    },
    paladin: {
        id: "paladin",
        name: "Paladin",
        description: "Guerrier sacré qui utilise la Lumière pour protéger ses alliés et punir ses ennemis.",
        primaryStat: "strength",
        icon: "🛡️",
        color: "#F58CBA",
        baseHP: 110,
        baseMP: 80,
        availableFor: {
            alliance: ["human", "dwarf", "draenei"],
            horde: ["blood-elf", "tauren"],
        },
        energyName: "💙 Mana",
        armorType: "plate",
        weaponType: ["sword", "mace"],
    },
    hunter: {
        id: "hunter",
        name: "Chasseur",
        description: "Maître du tir à distance et compagnon des bêtes sauvages.",
        primaryStat: "agility",
        icon: "🏹",
        color: "#ABD473",
        baseHP: 100,
        baseMP: 100,
        availableFor: {
            alliance: ["human", "dwarf", "night-elf", "draenei", "worgen", "gnome"],
            horde: ["orc", "undead", "tauren", "troll", "blood-elf", "goblin"],
        },
        energyName: "🎯 Focus",
        armorType: "mail",
        weaponType: ["bow"],
    },
    rogue: {
        id: "rogue",
        name: "Voleur",
        description: "Assassin furtif spécialisé dans les attaques sournoises et les coups critiques.",
        primaryStat: "agility",
        icon: "🗡️",
        color: "#FFF569",
        baseHP: 95,
        baseMP: 90,
        availableFor: {
            alliance: ["human", "dwarf", "night-elf", "gnome", "worgen"],
            horde: ["orc", "undead", "troll", "blood-elf", "goblin"],
        },
        energyName: "⚡ Énergie",
        armorType: "leather",
        weaponType: ["sword"],
    },
    priest: {
        id: "priest",
        name: "Prêtre",
        description: "Manipule la magie sacrée et de l'ombre pour soigner ou blesser.",
        primaryStat: "intellect",
        icon: "✨",
        color: "#FFFFFF",
        baseHP: 80,
        baseMP: 120,
        availableFor: {
            alliance: ["human", "dwarf", "night-elf", "draenei", "worgen"],
            horde: ["undead", "troll", "blood-elf", "goblin"],
        },
        energyName: "💙 Mana",
        armorType: "cloth",
        weaponType: ["staff"],
    },
    shaman: {
        id: "shaman",
        name: "Chaman",
        description: "Invoque le pouvoir des éléments et des esprits ancestraux.",
        primaryStat: "intellect",
        icon: "⚡",
        color: "#0070DE",
        baseHP: 95,
        baseMP: 110,
        availableFor: {
            alliance: ["draenei"],
            horde: ["orc", "tauren", "troll", "goblin"],
        },
        energyName: "💙 Mana",
        armorType: "mail",
        weaponType: ["mace", "staff"],
    },
    mage: {
        id: "mage",
        name: "Mage",
        description: "Maître des arcanes, du feu et du givre, capable de manipuler les forces magiques.",
        primaryStat: "intellect",
        icon: "🔮",
        color: "#69CCF0",
        baseHP: 75,
        baseMP: 130,
        availableFor: {
            alliance: ["human", "dwarf", "night-elf", "gnome", "draenei", "worgen"],
            horde: ["orc", "undead", "troll", "blood-elf", "goblin"],
        },
        energyName: "💙 Mana",
        armorType: "cloth",
        weaponType: ["staff"],
    },
    warlock: {
        id: "warlock",
        name: "Démoniste",
        description: "Invoque des démons et utilise la magie de l'ombre et du feu démoniaque.",
        primaryStat: "intellect",
        icon: "👿",
        color: "#9482C9",
        baseHP: 85,
        baseMP: 120,
        availableFor: {
            alliance: ["human", "dwarf", "gnome", "worgen"],
            horde: ["orc", "undead", "blood-elf", "goblin"],
        },
        energyName: "💙 Mana",
        armorType: "cloth",
        weaponType: ["staff"],
    },
    druid: {
        id: "druid",
        name: "Druide",
        description: "Transformiste de la nature capable de prendre plusieurs formes animales.",
        primaryStat: "intellect",
        icon: "🌿",
        color: "#FF7D0A",
        baseHP: 90,
        baseMP: 110,
        availableFor: {
            alliance: ["night-elf", "worgen"],
            horde: ["tauren", "troll"],
        },
        energyName: "💙 Mana",
        armorType: "leather",
        weaponType: ["staff", "mace"],
    },
    "death-knight": {
        id: "death-knight",
        name: "Chevalier de la mort",
        description: "Guerrier impie maniant les pouvoirs de la mort et de la glace.",
        primaryStat: "strength",
        icon: "💀",
        color: "#C41F3B",
        baseHP: 115,
        baseMP: 100,
        availableFor: {
            alliance: ["human", "dwarf", "night-elf", "gnome", "draenei", "worgen"],
            horde: ["orc", "undead", "tauren", "troll", "blood-elf", "goblin"],
        },
        energyName: "🌀 Runes",
        armorType: "plate",
        weaponType: ["sword", "axe", "mace"],
    },
};
export const randomClassInfo = () => {
    return CLASSES[Object.keys(CLASSES)[Math.floor(Math.random() * Object.keys(CLASSES).length)]];
};
// Races disponibles
export const RACES = {
    // Alliance
    human: {
        id: "human",
        name: "Humain",
        description: "Peuple courageux et déterminé de Hurlevent.",
        faction: "alliance",
        icon: "👨",
        bonuses: { strength: 2, agility: 1, intellect: 2, stamina: 2 },
    },
    dwarf: {
        id: "dwarf",
        name: "Nain",
        description: "Race ancienne et robuste de Forgefer.",
        faction: "alliance",
        icon: "🧔",
        bonuses: { strength: 3, stamina: 4, agility: 1 },
    },
    "night-elf": {
        id: "night-elf",
        name: "Elfe de la nuit",
        description: "Ancien peuple mystique de Kalimdor.",
        faction: "alliance",
        icon: "🧝",
        bonuses: { agility: 4, intellect: 1, stamina: 1 },
    },
    gnome: {
        id: "gnome",
        name: "Gnome",
        description: "Inventeurs ingénieux de Gnomeregan.",
        faction: "alliance",
        icon: "🧙",
        bonuses: { intellect: 4, agility: 2 },
    },
    draenei: {
        id: "draenei",
        name: "Draeneï",
        description: "Réfugiés nobles guidés par la Lumière.",
        faction: "alliance",
        icon: "👽",
        bonuses: { strength: 2, intellect: 2, stamina: 2 },
    },
    worgen: {
        id: "worgen",
        name: "Worgen",
        description: "Humains maudits transformés en loups-garous.",
        faction: "alliance",
        icon: "🐺",
        bonuses: { strength: 2, agility: 3, stamina: 2 },
    },
    // Horde
    orc: {
        id: "orc",
        name: "Orc",
        description: "Guerriers féroces d'Orgrimmar.",
        faction: "horde",
        icon: "👹",
        bonuses: { strength: 4, stamina: 3 },
    },
    undead: {
        id: "undead",
        name: "Mort-vivant",
        description: "Les Réprouvés, libérés du Fléau.",
        faction: "horde",
        icon: "🧟",
        bonuses: { intellect: 2, agility: 2, stamina: 2 },
    },
    tauren: {
        id: "tauren",
        name: "Tauren",
        description: "Géants paisibles des plaines de Mulgore.",
        faction: "horde",
        icon: "🐮",
        bonuses: { strength: 3, stamina: 5 },
    },
    troll: {
        id: "troll",
        name: "Troll",
        description: "Chasseurs rusés des Îles de l'Écho.",
        faction: "horde",
        icon: "🗿",
        bonuses: { agility: 3, intellect: 1, stamina: 2 },
    },
    "blood-elf": {
        id: "blood-elf",
        name: "Elfe de sang",
        description: "Anciens Haut-Elfes assoiffés de magie.",
        faction: "horde",
        icon: "🧝‍♀️",
        bonuses: { intellect: 4, agility: 2 },
    },
    goblin: {
        id: "goblin",
        name: "Gobelin",
        description: "Marchands malins et ingénieux.",
        faction: "horde",
        icon: "👺",
        bonuses: { intellect: 3, agility: 3 },
    },
};
// Obtenir les races disponibles pour une faction
export const getRacesByFaction = (faction) => {
    return Object.values(RACES).filter((race) => race.faction === faction);
};
// Obtenir les classes disponibles pour une race
export const getClassesForRace = (race, faction) => {
    return Object.values(CLASSES).filter((classInfo) => classInfo.availableFor[faction].includes(race));
};
